#!/usr/bin/env python
import rospy
import json
import pymongo

from geometry_msgs.msg import PoseStamped, Pose
from wire_msgs.msg import WorldState
from sensor_msgs.msg import JointState

from lingua_world.srv import Assert, AssertResponse
from lingua_world.srv import FindObjects, FindObjectsResponse
from lingua_world.srv import GetObjectPose, GetObjectPoseResponse

from std_srvs.srv import Empty

import lingua_pddl as pddl
from lingua_kb.srv import Tell, TellRequest

class World:
  def __init__(self):
    self.client = pymongo.MongoClient()
    self.db = self.client.lingua

    self.collection = self.db.objects

    self.sub_state = rospy.Subscriber('/world_state', WorldState, self.state_cb)

    self.srv_clear = rospy.Service('/lingua/world/clear', Empty, self.clear_cb)
    
    self.srv_pose = rospy.Service('/lingua/world/get_pose', GetObjectPose, self.get_pose_cb)

    self.kb_tell = rospy.ServiceProxy('/kb/tell', Tell)
  
  def state_cb(self, msg):
    for obj in msg.objects:
      entry = {
        'object_id': str(obj.ID),
        'attributes': [],
        'transient': True
      }

      for prop in obj.properties:
        if prop.attribute == 'position':
          entry['position'] = {
            'header': {
              'frame_id': msg.header.frame_id,
              'stamp': rospy.Time.now().to_sec()
            },
            'pose': {
              'position': {
                'x': prop.pdf.data[1],
                'y': prop.pdf.data[2],
                'z': prop.pdf.data[3]
              },
              'orientation': {
                'x': 0,
                'y': 0,
                'z': 0,
                'w': 1
              }
            }
          }
        else:
          entry['attributes'].append({'key': prop.attribute, 'value': prop.pdf.values})
                
      self.collection.replace_one({'object_id': entry['object_id']}, entry, upsert=True)
     
  def get_pose_cb(self, req):
    obj = self.collection.find_one({'object_id': req.object_id})
    
    if not obj:
      raise rospy.ServiceException('Unknown object with id: {}'.format(req.object_id))

    data = obj['position']
    ps = PoseStamped()
    
    ps.header.frame_id = data['header']['frame_id']
    ps.header.stamp = rospy.Time.from_sec(data['header']['stamp'])

    ps.pose.position.x = data['pose']['position']['x']
    ps.pose.position.y = data['pose']['position']['y']
    ps.pose.position.z = data['pose']['position']['z']
    
    ps.pose.orientation.w = 1

    return GetObjectPoseResponse(pose_stamped=ps)

  def clear_cb(self, req):
    self.collection.delete_many({'transient': True})


def main():
  rospy.init_node('world_model')
  world = World()
  rospy.spin()

if __name__ == '__main__':
  main()